<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => '',
    'Age' => 'Возраст',
    'Applicant ID' => 'ID соискателя',
    'Applicants' => 'Соискатели',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалеить эту запись?',
    'Auth Key' => 'Ключ авторизации',
    'Child' => '',
    'Content' => '@@Содержимое@@',
    'Create' => 'Создать',
    'Create Applicant' => 'Создать соискателя',
    'Create Currency' => 'Создать валюту',
    'Create Employer' => 'Создать работодателя',
    'Create Location' => 'Создать место',
    'Create Resume' => 'Создать резюме',
    'Create Scope' => 'Создать сферу деятельности',
    'Create Skill' => 'Создать навык',
    'Create User' => 'Создать пользователя',
    'Create Vacancy' => 'Создать вакансию',
    'Create applicant' => '',
    'Create location' => '',
    'Create resume' => '',
    'Create scope' => '',
    'Create skill' => '',
    'Create vacancy' => '',
    'Created At' => 'Создано в',
    'Currencies' => 'Валюты',
    'Data' => '',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Email' => '',
    'Employer ID' => '',
    'Employers' => 'Работодатели',
    'English' => '@@Английский@@',
    'First Name' => 'Имя',
    'Gii' => '@@@@',
    'Home' => '@@Главная@@',
    'ID' => '',
    'Iso4217' => 'ISO 4217',
    'Item Name' => '',
    'Language' => 'Язык',
    'Last Name' => 'Фамилия',
    'Level' => 'Уровень',
    'Location ID' => 'ID',
    'Locations' => 'Места',
    'Login' => '',
    'Login Form' => '',
    'Manager' => '',
    'Name' => '',
    'Parent' => '',
    'Parent ID' => 'ID',
    'Password' => 'Пароль',
    'Password Hash' => '',
    'Phone' => 'Телефон',
    'Reset' => 'Сброс',
    'Resume ID' => 'ID',
    'Resumes' => 'Резюме',
    'Role' => '',
    'Rule Name' => '',
    'Russian' => '@@Русский@@',
    'Salary Amount' => 'Зарплата',
    'Salary Currency ID' => 'ID',
    'Salary From' => 'Зарплата от',
    'Salary To' => 'Зарплата до',
    'Scope ID' => 'ID',
    'Scopes' => 'Сферы деятельности',
    'Search' => 'Поиск',
    'Site Url' => 'URL сайта',
    'Skill ID' => 'ID',
    'Skills' => 'Навыки',
    'Title' => 'Заголовок',
    'Type' => '',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => '',
    'Updated At' => 'Обновлено в',
    'User ID' => '',
    'Username' => '',
    'Users' => 'Пользователи',
    'Vacancies' => 'Вакансии',
    'Vacancy ID' => '',
];
