<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => '',
    'Applicant ID' => '',
    'Applicants' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Content' => '',
    'Create' => '',
    'Create Applicant' => '',
    'Create Currency' => '',
    'Create Employer' => '',
    'Create Location' => '',
    'Create Resume' => '',
    'Create Scope' => '',
    'Create Skill' => '',
    'Create User' => '',
    'Create Vacancy' => '',
    'Created At' => '',
    'Currencies' => '',
    'Delete' => '',
    'Description' => '',
    'Email' => '',
    'Employer ID' => '',
    'Employers' => '',
    'English' => '',
    'First Name' => '',
    'Gii' => '',
    'Home' => '',
    'ID' => '',
    'Iso4217' => '',
    'Language' => '',
    'Last Name' => '',
    'Level' => '',
    'Location ID' => '',
    'Locations' => '',
    'Parent ID' => '',
    'Password' => '',
    'Password Hash' => '',
    'Phone' => '',
    'Reset' => '',
    'Resume ID' => '',
    'Resumes' => '',
    'Russian' => '',
    'Salary Amount' => '',
    'Salary Currency ID' => '',
    'Salary From' => '',
    'Salary To' => '',
    'Scope ID' => '',
    'Scopes' => '',
    'Search' => '',
    'Site Url' => '',
    'Skill ID' => '',
    'Skills' => '',
    'Title' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Username' => '',
    'Users' => '',
    'Vacancies' => '',
    'Vacancy ID' => '',
];
